# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
# config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.box = "generic/debian11"
  config.ssh.insert_key = false

  config.vm.define "flask" do |app|
    app.vm.hostname = "flask.test"
    app.vm.network :private_network, ip: "192.168.56.10"
  end

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
  end

  # Ansible provisioning.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
