"""added comment to workout

Revision ID: a4e364816e04
Revises: aa46fd736d13
Create Date: 2019-10-08 14:37:26.295577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e364816e04'
down_revision = 'aa46fd736d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('comment', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'comment')
    # ### end Alembic commands ###
