"""change comment length to 40

Revision ID: cfb411bacd3d
Revises: 6935aa5ddd77
Create Date: 2023-07-06 11:14:20.743768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb411bacd3d'
down_revision = '6935aa5ddd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###
